CREATE TABLE "pakke_tiltak" (
	"id" text PRIMARY KEY NOT NULL,
	"aktor" text NOT NULL,
	"title" text NOT NULL,
	"steg" text NOT NULL,
	"innsats" integer NOT NULL,
	"effekt" integer NOT NULL,
	"tier" text NOT NULL,
	"kjerne" boolean DEFAULT false NOT NULL,
	"hypotese" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"blokkert_av" text,
	"guardrail" text,
	"forgood" text,
	"toveis" text,
	"hvorfor" text,
	"updated_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "pakke_tiltak_aktor_check" CHECK ("pakke_tiltak"."aktor" in ('ag', 'sm')),
	CONSTRAINT "pakke_tiltak_tier_check" CHECK ("pakke_tiltak"."tier" in ('pakke1', 'vurder', 'senere')),
	CONSTRAINT "pakke_tiltak_innsats_range" CHECK ("pakke_tiltak"."innsats" between 1 and 3),
	CONSTRAINT "pakke_tiltak_effekt_range" CHECK ("pakke_tiltak"."effekt" between 1 and 3),
	CONSTRAINT "pakke_tiltak_title_length" CHECK (char_length("pakke_tiltak"."title") <= 200),
	CONSTRAINT "pakke_tiltak_version_positive" CHECK ("pakke_tiltak"."version" > 0)
);
